# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rdi_face_verification_python
else:
    import _rdi_face_verification_python

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _rdi_face_verification_python.delete_SwigPyIterator

    def value(self):
        return _rdi_face_verification_python.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _rdi_face_verification_python.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _rdi_face_verification_python.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _rdi_face_verification_python.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _rdi_face_verification_python.SwigPyIterator_equal(self, x)

    def copy(self):
        return _rdi_face_verification_python.SwigPyIterator_copy(self)

    def next(self):
        return _rdi_face_verification_python.SwigPyIterator_next(self)

    def __next__(self):
        return _rdi_face_verification_python.SwigPyIterator___next__(self)

    def previous(self):
        return _rdi_face_verification_python.SwigPyIterator_previous(self)

    def advance(self, n):
        return _rdi_face_verification_python.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _rdi_face_verification_python.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _rdi_face_verification_python.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _rdi_face_verification_python.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _rdi_face_verification_python.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _rdi_face_verification_python.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _rdi_face_verification_python.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _rdi_face_verification_python:
_rdi_face_verification_python.SwigPyIterator_swigregister(SwigPyIterator)

class Point(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_rdi_face_verification_python.Point_x_get, _rdi_face_verification_python.Point_x_set)
    y = property(_rdi_face_verification_python.Point_y_get, _rdi_face_verification_python.Point_y_set)
    id = property(_rdi_face_verification_python.Point_id_get, _rdi_face_verification_python.Point_id_set)

    def __init__(self, *args):
        _rdi_face_verification_python.Point_swiginit(self, _rdi_face_verification_python.new_Point(*args))
    __swig_destroy__ = _rdi_face_verification_python.delete_Point

# Register Point in _rdi_face_verification_python:
_rdi_face_verification_python.Point_swigregister(Point)

class Rectangle(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    upper_left = property(_rdi_face_verification_python.Rectangle_upper_left_get, _rdi_face_verification_python.Rectangle_upper_left_set)
    bottom_right = property(_rdi_face_verification_python.Rectangle_bottom_right_get, _rdi_face_verification_python.Rectangle_bottom_right_set)
    id = property(_rdi_face_verification_python.Rectangle_id_get, _rdi_face_verification_python.Rectangle_id_set)

    def __init__(self, *args):
        _rdi_face_verification_python.Rectangle_swiginit(self, _rdi_face_verification_python.new_Rectangle(*args))

    def width(self):
        return _rdi_face_verification_python.Rectangle_width(self)

    def height(self):
        return _rdi_face_verification_python.Rectangle_height(self)

    def area(self):
        return _rdi_face_verification_python.Rectangle_area(self)
    __swig_destroy__ = _rdi_face_verification_python.delete_Rectangle

# Register Rectangle in _rdi_face_verification_python:
_rdi_face_verification_python.Rectangle_swigregister(Rectangle)

class RDI_Error(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    code = property(_rdi_face_verification_python.RDI_Error_code_get, _rdi_face_verification_python.RDI_Error_code_set)
    what = property(_rdi_face_verification_python.RDI_Error_what_get, _rdi_face_verification_python.RDI_Error_what_set)

    def __init__(self):
        _rdi_face_verification_python.RDI_Error_swiginit(self, _rdi_face_verification_python.new_RDI_Error())
    __swig_destroy__ = _rdi_face_verification_python.delete_RDI_Error

# Register RDI_Error in _rdi_face_verification_python:
_rdi_face_verification_python.RDI_Error_swigregister(RDI_Error)

class Image(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    RGB = _rdi_face_verification_python.Image_RGB
    BGR = _rdi_face_verification_python.Image_BGR
    GRAY = _rdi_face_verification_python.Image_GRAY
    BINARY = _rdi_face_verification_python.Image_BINARY

    def __init__(self):
        _rdi_face_verification_python.Image_swiginit(self, _rdi_face_verification_python.new_Image())
    __swig_destroy__ = _rdi_face_verification_python.delete_Image

    def clone(self):
        return _rdi_face_verification_python.Image_clone(self)

    @staticmethod
    def construct(*args):
        return _rdi_face_verification_python.Image_construct(*args)

    def save(self, arg2, overwrite=True):
        return _rdi_face_verification_python.Image_save(self, arg2, overwrite)

    def width(self):
        return _rdi_face_verification_python.Image_width(self)

    def height(self):
        return _rdi_face_verification_python.Image_height(self)

    def channels(self):
        return _rdi_face_verification_python.Image_channels(self)

    def binarize(self, inverse=False):
        return _rdi_face_verification_python.Image_binarize(self, inverse)

    def crop(self, *args):
        return _rdi_face_verification_python.Image_crop(self, *args)

    def get_pixel(self, x, y):
        return _rdi_face_verification_python.Image_get_pixel(self, x, y)

    def resize(self, ratio):
        return _rdi_face_verification_python.Image_resize(self, ratio)

    def resize_and_keep_aspect_ratio(self, max_side_length):
        return _rdi_face_verification_python.Image_resize_and_keep_aspect_ratio(self, max_side_length)

    def draw_rectangles(self, rect, color, thickness):
        return _rdi_face_verification_python.Image_draw_rectangles(self, rect, color, thickness)

    def draw_rectangle(self, rect, color, thickness):
        return _rdi_face_verification_python.Image_draw_rectangle(self, rect, color, thickness)

    def to_grayscale(self):
        return _rdi_face_verification_python.Image_to_grayscale(self)

    def convert_color(self, new_mode):
        return _rdi_face_verification_python.Image_convert_color(self, new_mode)

    def encode_to_jpg(self):
        return _rdi_face_verification_python.Image_encode_to_jpg(self)

    def encode_to_png(self):
        return _rdi_face_verification_python.Image_encode_to_png(self)
    mode = property(_rdi_face_verification_python.Image_mode_get, _rdi_face_verification_python.Image_mode_set)

# Register Image in _rdi_face_verification_python:
_rdi_face_verification_python.Image_swigregister(Image)

def Image_construct(*args):
    return _rdi_face_verification_python.Image_construct(*args)

class Image_Pixel(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    red = property(_rdi_face_verification_python.Image_Pixel_red_get, _rdi_face_verification_python.Image_Pixel_red_set)
    green = property(_rdi_face_verification_python.Image_Pixel_green_get, _rdi_face_verification_python.Image_Pixel_green_set)
    blue = property(_rdi_face_verification_python.Image_Pixel_blue_get, _rdi_face_verification_python.Image_Pixel_blue_set)

    def __init__(self):
        _rdi_face_verification_python.Image_Pixel_swiginit(self, _rdi_face_verification_python.new_Image_Pixel())
    __swig_destroy__ = _rdi_face_verification_python.delete_Image_Pixel

# Register Image_Pixel in _rdi_face_verification_python:
_rdi_face_verification_python.Image_Pixel_swigregister(Image_Pixel)

class ImageResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    result = property(_rdi_face_verification_python.ImageResult_result_get, _rdi_face_verification_python.ImageResult_result_set)
    error = property(_rdi_face_verification_python.ImageResult_error_get, _rdi_face_verification_python.ImageResult_error_set)

    def __init__(self):
        _rdi_face_verification_python.ImageResult_swiginit(self, _rdi_face_verification_python.new_ImageResult())
    __swig_destroy__ = _rdi_face_verification_python.delete_ImageResult

# Register ImageResult in _rdi_face_verification_python:
_rdi_face_verification_python.ImageResult_swigregister(ImageResult)

class RectangleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _rdi_face_verification_python.RectangleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _rdi_face_verification_python.RectangleVector___nonzero__(self)

    def __bool__(self):
        return _rdi_face_verification_python.RectangleVector___bool__(self)

    def __len__(self):
        return _rdi_face_verification_python.RectangleVector___len__(self)

    def __getslice__(self, i, j):
        return _rdi_face_verification_python.RectangleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _rdi_face_verification_python.RectangleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _rdi_face_verification_python.RectangleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _rdi_face_verification_python.RectangleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _rdi_face_verification_python.RectangleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _rdi_face_verification_python.RectangleVector___setitem__(self, *args)

    def pop(self):
        return _rdi_face_verification_python.RectangleVector_pop(self)

    def append(self, x):
        return _rdi_face_verification_python.RectangleVector_append(self, x)

    def empty(self):
        return _rdi_face_verification_python.RectangleVector_empty(self)

    def size(self):
        return _rdi_face_verification_python.RectangleVector_size(self)

    def swap(self, v):
        return _rdi_face_verification_python.RectangleVector_swap(self, v)

    def begin(self):
        return _rdi_face_verification_python.RectangleVector_begin(self)

    def end(self):
        return _rdi_face_verification_python.RectangleVector_end(self)

    def rbegin(self):
        return _rdi_face_verification_python.RectangleVector_rbegin(self)

    def rend(self):
        return _rdi_face_verification_python.RectangleVector_rend(self)

    def clear(self):
        return _rdi_face_verification_python.RectangleVector_clear(self)

    def get_allocator(self):
        return _rdi_face_verification_python.RectangleVector_get_allocator(self)

    def pop_back(self):
        return _rdi_face_verification_python.RectangleVector_pop_back(self)

    def erase(self, *args):
        return _rdi_face_verification_python.RectangleVector_erase(self, *args)

    def __init__(self, *args):
        _rdi_face_verification_python.RectangleVector_swiginit(self, _rdi_face_verification_python.new_RectangleVector(*args))

    def push_back(self, x):
        return _rdi_face_verification_python.RectangleVector_push_back(self, x)

    def front(self):
        return _rdi_face_verification_python.RectangleVector_front(self)

    def back(self):
        return _rdi_face_verification_python.RectangleVector_back(self)

    def assign(self, n, x):
        return _rdi_face_verification_python.RectangleVector_assign(self, n, x)

    def resize(self, *args):
        return _rdi_face_verification_python.RectangleVector_resize(self, *args)

    def insert(self, *args):
        return _rdi_face_verification_python.RectangleVector_insert(self, *args)

    def reserve(self, n):
        return _rdi_face_verification_python.RectangleVector_reserve(self, n)

    def capacity(self):
        return _rdi_face_verification_python.RectangleVector_capacity(self)
    __swig_destroy__ = _rdi_face_verification_python.delete_RectangleVector

# Register RectangleVector in _rdi_face_verification_python:
_rdi_face_verification_python.RectangleVector_swigregister(RectangleVector)

class ImageDataVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _rdi_face_verification_python.ImageDataVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _rdi_face_verification_python.ImageDataVector___nonzero__(self)

    def __bool__(self):
        return _rdi_face_verification_python.ImageDataVector___bool__(self)

    def __len__(self):
        return _rdi_face_verification_python.ImageDataVector___len__(self)

    def __getslice__(self, i, j):
        return _rdi_face_verification_python.ImageDataVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _rdi_face_verification_python.ImageDataVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _rdi_face_verification_python.ImageDataVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _rdi_face_verification_python.ImageDataVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _rdi_face_verification_python.ImageDataVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _rdi_face_verification_python.ImageDataVector___setitem__(self, *args)

    def pop(self):
        return _rdi_face_verification_python.ImageDataVector_pop(self)

    def append(self, x):
        return _rdi_face_verification_python.ImageDataVector_append(self, x)

    def empty(self):
        return _rdi_face_verification_python.ImageDataVector_empty(self)

    def size(self):
        return _rdi_face_verification_python.ImageDataVector_size(self)

    def swap(self, v):
        return _rdi_face_verification_python.ImageDataVector_swap(self, v)

    def begin(self):
        return _rdi_face_verification_python.ImageDataVector_begin(self)

    def end(self):
        return _rdi_face_verification_python.ImageDataVector_end(self)

    def rbegin(self):
        return _rdi_face_verification_python.ImageDataVector_rbegin(self)

    def rend(self):
        return _rdi_face_verification_python.ImageDataVector_rend(self)

    def clear(self):
        return _rdi_face_verification_python.ImageDataVector_clear(self)

    def get_allocator(self):
        return _rdi_face_verification_python.ImageDataVector_get_allocator(self)

    def pop_back(self):
        return _rdi_face_verification_python.ImageDataVector_pop_back(self)

    def erase(self, *args):
        return _rdi_face_verification_python.ImageDataVector_erase(self, *args)

    def __init__(self, *args):
        _rdi_face_verification_python.ImageDataVector_swiginit(self, _rdi_face_verification_python.new_ImageDataVector(*args))

    def push_back(self, x):
        return _rdi_face_verification_python.ImageDataVector_push_back(self, x)

    def front(self):
        return _rdi_face_verification_python.ImageDataVector_front(self)

    def back(self):
        return _rdi_face_verification_python.ImageDataVector_back(self)

    def assign(self, n, x):
        return _rdi_face_verification_python.ImageDataVector_assign(self, n, x)

    def resize(self, *args):
        return _rdi_face_verification_python.ImageDataVector_resize(self, *args)

    def insert(self, *args):
        return _rdi_face_verification_python.ImageDataVector_insert(self, *args)

    def reserve(self, n):
        return _rdi_face_verification_python.ImageDataVector_reserve(self, n)

    def capacity(self):
        return _rdi_face_verification_python.ImageDataVector_capacity(self)
    __swig_destroy__ = _rdi_face_verification_python.delete_ImageDataVector

# Register ImageDataVector in _rdi_face_verification_python:
_rdi_face_verification_python.ImageDataVector_swigregister(ImageDataVector)

VeryAgressive = _rdi_face_verification_python.VeryAgressive
Aggressive = _rdi_face_verification_python.Aggressive
Balanced = _rdi_face_verification_python.Balanced
class VerificationResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    face1 = property(_rdi_face_verification_python.VerificationResult_face1_get, _rdi_face_verification_python.VerificationResult_face1_set)
    face1_coordinates = property(_rdi_face_verification_python.VerificationResult_face1_coordinates_get, _rdi_face_verification_python.VerificationResult_face1_coordinates_set)
    face2 = property(_rdi_face_verification_python.VerificationResult_face2_get, _rdi_face_verification_python.VerificationResult_face2_set)
    face2_coordinates = property(_rdi_face_verification_python.VerificationResult_face2_coordinates_get, _rdi_face_verification_python.VerificationResult_face2_coordinates_set)
    verified = property(_rdi_face_verification_python.VerificationResult_verified_get, _rdi_face_verification_python.VerificationResult_verified_set)
    confidence = property(_rdi_face_verification_python.VerificationResult_confidence_get, _rdi_face_verification_python.VerificationResult_confidence_set)

    def __init__(self):
        _rdi_face_verification_python.VerificationResult_swiginit(self, _rdi_face_verification_python.new_VerificationResult())
    __swig_destroy__ = _rdi_face_verification_python.delete_VerificationResult

# Register VerificationResult in _rdi_face_verification_python:
_rdi_face_verification_python.VerificationResult_swigregister(VerificationResult)


def initialize_model(model_path):
    return _rdi_face_verification_python.initialize_model(model_path)

def deinitialize_model(model_path):
    return _rdi_face_verification_python.deinitialize_model(model_path)

def verify_face(image1, image2, model_path, verify_mode, id_face_verification=False):
    return _rdi_face_verification_python.verify_face(image1, image2, model_path, verify_mode, id_face_verification)

def get_model_information(model_path):
    return _rdi_face_verification_python.get_model_information(model_path)

def get_release_version():
    return _rdi_face_verification_python.get_release_version()
class VerificationOutput(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    result = property(_rdi_face_verification_python.VerificationOutput_result_get, _rdi_face_verification_python.VerificationOutput_result_set)
    error = property(_rdi_face_verification_python.VerificationOutput_error_get, _rdi_face_verification_python.VerificationOutput_error_set)

    def __init__(self):
        _rdi_face_verification_python.VerificationOutput_swiginit(self, _rdi_face_verification_python.new_VerificationOutput())
    __swig_destroy__ = _rdi_face_verification_python.delete_VerificationOutput

# Register VerificationOutput in _rdi_face_verification_python:
_rdi_face_verification_python.VerificationOutput_swigregister(VerificationOutput)

class PointVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _rdi_face_verification_python.PointVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _rdi_face_verification_python.PointVector___nonzero__(self)

    def __bool__(self):
        return _rdi_face_verification_python.PointVector___bool__(self)

    def __len__(self):
        return _rdi_face_verification_python.PointVector___len__(self)

    def __getslice__(self, i, j):
        return _rdi_face_verification_python.PointVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _rdi_face_verification_python.PointVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _rdi_face_verification_python.PointVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _rdi_face_verification_python.PointVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _rdi_face_verification_python.PointVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _rdi_face_verification_python.PointVector___setitem__(self, *args)

    def pop(self):
        return _rdi_face_verification_python.PointVector_pop(self)

    def append(self, x):
        return _rdi_face_verification_python.PointVector_append(self, x)

    def empty(self):
        return _rdi_face_verification_python.PointVector_empty(self)

    def size(self):
        return _rdi_face_verification_python.PointVector_size(self)

    def swap(self, v):
        return _rdi_face_verification_python.PointVector_swap(self, v)

    def begin(self):
        return _rdi_face_verification_python.PointVector_begin(self)

    def end(self):
        return _rdi_face_verification_python.PointVector_end(self)

    def rbegin(self):
        return _rdi_face_verification_python.PointVector_rbegin(self)

    def rend(self):
        return _rdi_face_verification_python.PointVector_rend(self)

    def clear(self):
        return _rdi_face_verification_python.PointVector_clear(self)

    def get_allocator(self):
        return _rdi_face_verification_python.PointVector_get_allocator(self)

    def pop_back(self):
        return _rdi_face_verification_python.PointVector_pop_back(self)

    def erase(self, *args):
        return _rdi_face_verification_python.PointVector_erase(self, *args)

    def __init__(self, *args):
        _rdi_face_verification_python.PointVector_swiginit(self, _rdi_face_verification_python.new_PointVector(*args))

    def push_back(self, x):
        return _rdi_face_verification_python.PointVector_push_back(self, x)

    def front(self):
        return _rdi_face_verification_python.PointVector_front(self)

    def back(self):
        return _rdi_face_verification_python.PointVector_back(self)

    def assign(self, n, x):
        return _rdi_face_verification_python.PointVector_assign(self, n, x)

    def resize(self, *args):
        return _rdi_face_verification_python.PointVector_resize(self, *args)

    def insert(self, *args):
        return _rdi_face_verification_python.PointVector_insert(self, *args)

    def reserve(self, n):
        return _rdi_face_verification_python.PointVector_reserve(self, n)

    def capacity(self):
        return _rdi_face_verification_python.PointVector_capacity(self)
    __swig_destroy__ = _rdi_face_verification_python.delete_PointVector

# Register PointVector in _rdi_face_verification_python:
_rdi_face_verification_python.PointVector_swigregister(PointVector)



